var annotated_dup =
[
    [ "BackgroundLoop", "class_background_loop.html", "class_background_loop" ],
    [ "BackgroundScroller", "class_background_scroller.html", "class_background_scroller" ],
    [ "backgroundScroller", "classbackground_scroller.html", "classbackground_scroller" ],
    [ "ButtonSound", "class_button_sound.html", "class_button_sound" ],
    [ "CameraBoundaryReset", "class_camera_boundary_reset.html", "class_camera_boundary_reset" ],
    [ "CameraFollow", "class_camera_follow.html", "class_camera_follow" ],
    [ "CollisionReset", "class_collision_reset.html", null ],
    [ "GameManager", "class_game_manager.html", "class_game_manager" ],
    [ "labDoMenu", "classlab_do_menu.html", "classlab_do_menu" ],
    [ "labDoMenuL", "classlab_do_menu_l.html", "classlab_do_menu_l" ],
    [ "menuDoLab", "classmenu_do_lab.html", "classmenu_do_lab" ],
    [ "menuDoSkok", "classmenu_do_skok.html", "classmenu_do_skok" ],
    [ "MenuPanelController", "class_menu_panel_controller.html", "class_menu_panel_controller" ],
    [ "PauseManager", "class_pause_manager.html", "class_pause_manager" ],
    [ "PauseMenuController", "class_pause_menu_controller.html", "class_pause_menu_controller" ],
    [ "PlatformPassOnJumpWithoutVelocity", "class_platform_pass_on_jump_without_velocity.html", null ],
    [ "PlatformScoreTrigger", "class_platform_score_trigger.html", "class_platform_score_trigger" ],
    [ "PlatformSpawner", "class_platform_spawner.html", null ],
    [ "Platformspawner", "class_platformspawner.html", "class_platformspawner" ],
    [ "platformSpawner", "classplatform_spawner.html", "classplatform_spawner" ],
    [ "PlayButtonController", "class_play_button_controller.html", "class_play_button_controller" ],
    [ "PlayerBounce", "class_player_bounce.html", "class_player_bounce" ],
    [ "PlayerFallReset", "class_player_fall_reset.html", null ],
    [ "PlayerMovement", "class_player_movement.html", "class_player_movement" ],
    [ "PlayerPlatformPassThroughWithoutVelocity", "class_player_platform_pass_through_without_velocity.html", null ],
    [ "PointTrigger", "class_point_trigger.html", "class_point_trigger" ],
    [ "PotrzebyManager", "class_potrzeby_manager.html", null ],
    [ "PunktyManL", "class_punkty_man_l.html", "class_punkty_man_l" ],
    [ "ScoreManager", "class_score_manager.html", "class_score_manager" ],
    [ "tło", "classt_xC5_x82o.html", null ],
    [ "tło_2Scroller", "classt_xC5_x82o__2_scroller.html", "classt_xC5_x82o__2_scroller" ],
    [ "Update_PlayerController", "class_update___player_controller.html", "class_update___player_controller" ],
    [ "Update_playerController", "class_update__player_controller.html", "class_update__player_controller" ],
    [ "ZachowaniePaskow", "class_zachowanie_paskow.html", "class_zachowanie_paskow" ],
    [ "zmianaSkina", "classzmiana_skina.html", "classzmiana_skina" ]
];