var hierarchy =
[
    [ "MonoBehaviour", null, [
      [ "BackgroundLoop", "class_background_loop.html", null ],
      [ "BackgroundScroller", "class_background_scroller.html", null ],
      [ "ButtonSound", "class_button_sound.html", null ],
      [ "CameraBoundaryReset", "class_camera_boundary_reset.html", null ],
      [ "CameraFollow", "class_camera_follow.html", null ],
      [ "CollisionReset", "class_collision_reset.html", null ],
      [ "GameManager", "class_game_manager.html", null ],
      [ "MenuPanelController", "class_menu_panel_controller.html", null ],
      [ "PauseManager", "class_pause_manager.html", null ],
      [ "PauseMenuController", "class_pause_menu_controller.html", null ],
      [ "PlatformPassOnJumpWithoutVelocity", "class_platform_pass_on_jump_without_velocity.html", null ],
      [ "PlatformScoreTrigger", "class_platform_score_trigger.html", null ],
      [ "PlatformSpawner", "class_platform_spawner.html", null ],
      [ "Platformspawner", "class_platformspawner.html", null ],
      [ "PlayButtonController", "class_play_button_controller.html", null ],
      [ "PlayerBounce", "class_player_bounce.html", null ],
      [ "PlayerFallReset", "class_player_fall_reset.html", null ],
      [ "PlayerMovement", "class_player_movement.html", null ],
      [ "PlayerPlatformPassThroughWithoutVelocity", "class_player_platform_pass_through_without_velocity.html", null ],
      [ "PointTrigger", "class_point_trigger.html", null ],
      [ "PotrzebyManager", "class_potrzeby_manager.html", null ],
      [ "PunktyManL", "class_punkty_man_l.html", null ],
      [ "ScoreManager", "class_score_manager.html", null ],
      [ "Update_PlayerController", "class_update___player_controller.html", null ],
      [ "Update_playerController", "class_update__player_controller.html", null ],
      [ "ZachowaniePaskow", "class_zachowanie_paskow.html", null ],
      [ "backgroundScroller", "classbackground_scroller.html", null ],
      [ "labDoMenu", "classlab_do_menu.html", null ],
      [ "labDoMenuL", "classlab_do_menu_l.html", null ],
      [ "menuDoLab", "classmenu_do_lab.html", null ],
      [ "menuDoSkok", "classmenu_do_skok.html", null ],
      [ "platformSpawner", "classplatform_spawner.html", null ],
      [ "tło", "classt_xC5_x82o.html", null ],
      [ "tło_2Scroller", "classt_xC5_x82o__2_scroller.html", null ],
      [ "zmianaSkina", "classzmiana_skina.html", null ]
    ] ]
];